[package]
name = "hello"
version = "0.1.0"
authors = ["lim <lumeng689@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.3"